//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TermProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class BY_RAM
    {
        public string Name { get; set; }
        public int Price { get; set; }
        public string Capacity { get; set; }
        public string OS { get; set; }
        public string Manufacturer { get; set; }
    }
}
