//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TermProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dtbs15Entities : DbContext
    {
        public dtbs15Entities()
            : base("name=dtbs15Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Back_Camera> Back_Camera { get; set; }
        public virtual DbSet<Browser> Browsers { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Connectivity> Connectivities { get; set; }
        public virtual DbSet<Display> Displays { get; set; }
        public virtual DbSet<Front_Camera> Front_Camera { get; set; }
        public virtual DbSet<OperatingSystem> OperatingSystems { get; set; }
        public virtual DbSet<Processor> Processors { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<RAM> RAMs { get; set; }
        public virtual DbSet<ROM> ROMs { get; set; }
        public virtual DbSet<USB> USBs { get; set; }
        public virtual DbSet<By_Brand> By_Brands { get; set; }
        public virtual DbSet<Price_60000> Price_60000 { get; set; }
        public virtual DbSet<View_Name> View_Name { get; set; }
        public virtual DbSet<BY_BackCamera> BY_BackCamera { get; set; }
        public virtual DbSet<BY_BackCamera16MP> BY_BackCamera16MP { get; set; }
        public virtual DbSet<By_Browser> By_Browser { get; set; }
        public virtual DbSet<By_Display> By_Display { get; set; }
        public virtual DbSet<By_OS> By_OS { get; set; }
        public virtual DbSet<BY_RAM> BY_RAM { get; set; }
    }
}
