//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TermProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int CategoryId { get; set; }
        public System.DateTime Add_Date { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
        public bool Wifi { get; set; }
        public double Size { get; set; }
        public string Resolution { get; set; }
        public bool CardSupport { get; set; }
        public int Price { get; set; }
        public byte[] Image1 { get; set; }
        public byte[] Image2 { get; set; }
        public byte[] Image3 { get; set; }
        public int RamId { get; set; }
        public Nullable<int> FcamId { get; set; }
        public Nullable<int> BcamId { get; set; }
        public int DPT_Id { get; set; }
        public int Browser_Id { get; set; }
        public int USB_Id { get; set; }
        public int OS_Id { get; set; }
        public int Connectivity_Id { get; set; }
        public int ROM_Id { get; set; }
        public int Processor_Id { get; set; }
    
        public virtual Back_Camera Back_Camera { get; set; }
        public virtual Browser Browser { get; set; }
        public virtual Category Category { get; set; }
        public virtual Connectivity Connectivity { get; set; }
        public virtual Display Display { get; set; }
        public virtual Front_Camera Front_Camera { get; set; }
        public virtual OperatingSystem OperatingSystem { get; set; }
        public virtual OperatingSystem OperatingSystem1 { get; set; }
        public virtual RAM RAM { get; set; }
        public virtual ROM ROM { get; set; }
        public virtual USB USB { get; set; }
    }
}
